begin transaction;

create schema ALCE;

/*SEQUENCIA*/
CREATE SEQUENCE ALCE.SEQUENCE_USUARIO_CUSER_CODIGO
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;


/*TABELAS*/
CREATE TABLE ALCE.TBUSUARIO(
    CUSER_CODIGO bigint not null default nextval('ALCE.SEQUENCE_USUARIO_CUSER_CODIGO'),
    NUSER_NOME text not null,
    NUSER_CIDADE text not null,
    NUSER_ESTADO text not null,
    NUSER_ESCOLARIDADE text not null,
    TUSER_NASCIMENTO timestamp not null,
    CUSER_IMEI1 text not null,
    CUSER_IMEI2 text not null,
    NUSER_MODELO text not null,
    TUSER_CRIACAO timestamp,
    TUSER_EXCLUSAO timestamp,
    TUSER_ULAT timestamp

);

/*CHAVES PRIMARIAS*/
ALTER TABLE ALCE.TBUSUARIO ADD CONSTRAINT PUSER_CHAVE_PRIMARIA PRIMARY KEY(CUSER_CODIGO);

/*COMENTÁRIOS*/
COMMENT ON TABLE ALCE.TBUSUARIO IS 'Onde ficam os usuários.';
COMMENT ON COLUMN ALCE.TBUSUARIO.NUSER_NOME IS 'Nome do usuário.';
COMMENT ON COLUMN ALCE.TBUSUARIO.NUSER_CIDADE IS 'Cidade do usuário.';
COMMENT ON COLUMN ALCE.TBUSUARIO.NUSER_ESTADO IS 'Estado do usuário.';
COMMENT ON COLUMN ALCE.TBUSUARIO.NUSER_ESCOLARIDADE IS 'Escolaridade do usuário.';
COMMENT ON COLUMN ALCE.TBUSUARIO.TUSER_NASCIMENTO IS 'Data de nascimento do usuário..';
COMMENT ON COLUMN ALCE.TBUSUARIO.CUSER_IMEI1 IS 'Imei 1 do celular do usuário.';
COMMENT ON COLUMN ALCE.TBUSUARIO.CUSER_IMEI2 IS 'Imei 2 do celular do usuário.';
COMMENT ON COLUMN ALCE.TBUSUARIO.NUSER_MODELO IS 'Modelo do celular do usuário.';
COMMENT ON COLUMN ALCE.TBUSUARIO.TUSER_CRIACAO IS 'Data de criação.';
COMMENT ON COLUMN ALCE.TBUSUARIO.TUSER_EXCLUSAO IS 'Data de exclusão.';
COMMENT ON COLUMN ALCE.TBUSUARIO.TUSER_ULAT IS 'Data de ultima alteração.';

/*DADOS INICIAIS*/

INSERT INTO ALCE.TBUSUARIO(
    CUSER_CODIGO,
    NUSER_NOME,
    NUSER_CIDADE,
    NUSER_ESTADO,
    NUSER_ESCOLARIDADE,
    TUSER_NASCIMENTO,
    CUSER_IMEI1,
    CUSER_IMEI2,
    NUSER_MODELO,
    TUSER_CRIACAO

) VALUES (
    1,
    'SISTEMA',
    'PAULISTA',
    'PERNAMBUCO',
    'SUPERIOR COMPLETO',
    CURRENT_TIMESTAMP,
    'XXXXXXXXXXXXXXX1',
    'XXXXXXXXXXXXXXX2',
    'XXXXXXXX',
    CURRENT_TIMESTAMP
);

commit;