spring.application.name=alertacellgcmr
spring.datasource.url=jdbc:postgresql://localhost:5432/dbprojetosvillar
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
